### ISSUE TITLE
Error in Console - No Game Errors

### ISSUE THREAD

**Issue by Lukeha44** [novucs/factions-top#11]
```
[11:36:07 ERROR]: Error occurred while enabling FactionsTop v1.0.8 (Is it up to date?)
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:h2:./plugins/FactionsTop/database
        at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:88) ~[?:?]
        at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:298) ~[?:?]
        at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:91) ~[?:?]
        at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:101) ~[?:?]
        at net.novucs.ftop.shade.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
        at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:28) ~[?:?]
        at net.novucs.ftop.FactionsTopPlugin.loadDatabase(FactionsTopPlugin.java:177) ~[?:?]
        at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:124) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [Spigot.jar:git-Spigot-870264a-0a645a2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(Unknown Source) ~[?:1.8.0_65]
        at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:81) ~[?:?]
        ... 18 more
```

**Comment by novucs** [comment]
H2 must be downloaded under root/lib and loaded into the JVM. If you're still having issues then please add the automatically downloaded H2 jar to the classpath in your start script.
