### ISSUE TITLE
Using SavageFactions fork (other plugins run it fine they didnt change)

### ISSUE THREAD

**Issue by Taleeko** [novucs/factions-top#119]
> [12:10:38 INFO]: [FactionsTop] Enabling FactionsTop v1.2.0
> [12:10:38 ERROR]: Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/RelationParticipator
at net.novucs.ftop.FactionsTopPlugin.loadFactionsHook(FactionsTopPlugin.java:333) ~[?:?]
at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:122) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-TacoSpigot-04511af6]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [server.jar:git-TacoSpigot-04511af6]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [server.jar:git-TacoSpigot-04511af6]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) [server.jar:git-TacoSpigot-04511af6]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) [server.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:427) [server.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:391) [server.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:346) [server.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276) [server.jar:git-TacoSpigot-04511af6]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:593) [server.jar:git-TacoSpigot-04511af6]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.RelationParticipator
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[server.jar:git-TacoSpigot-04511af6]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-TacoSpigot-04511af6]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 13 more

**Comment by Phoenix616** [comment]
Please provide the version of factions that you are using.
