### ISSUE TITLE
FTOP not working with EpicSpawners

### ISSUE THREAD

**Issue by Cheesearmada** [novucs/factions-top#122]
Error Log:
[19:08:25 ERROR]: [Minecraft] Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NoSuchMethodError: com.songoda.epicspawners.EpicSpawners.getApi()Lcom/songoda/epicspawners/API/EpicSpawnersAPI;
	at net.novucs.ftop.hook.EpicSpawnersHook.initialize(EpicSpawnersHook.java:31) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.loadSpawnerStackerHook(FactionsTopPlugin.java:285) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:130) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) 
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) 
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) 
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:313) 
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:272) 
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) 
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) 
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) 
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) 
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) 
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

__________

[19:08:25 ERROR]: [Minecraft] Error occurred while disabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NullPointerException
	at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:177) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[flux.jar:FluxSpigot-04511af6]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) 
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) 
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) 
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:313) 
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:272) 
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) 
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) 
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) 
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) 
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) 
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

___________

Server Version: 1.8.8
FTOP Version: 1.2.0
EpicSpawners Version: 6.2

**Comment by Phoenix616** [comment]
Could you please try the latest development build available [here](https://ci.minebench.de/view/Various/job/FactionsTop/) and see if that already fixes your issue?

**Comment by cachondagames** [comment]
Im having the same error and tried the dev build still throwing the same expection

**Comment by cachondagames** [comment]
[08:40:06] [Server thread/ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/songoda/epicspawners/EpicSpawners
	at net.novucs.ftop.hook.EpicSpawnersHook.initialize(EpicSpawnersHook.java:30) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.loadSpawnerStackerHook(FactionsTopPlugin.java:286) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:131) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: com.songoda.epicspawners.EpicSpawners
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 14 more

**Comment by Cheesearmada** [comment]
Same, I tried the dev build and its throwing a similar issue.

**Comment by Oscaz** [comment]
What version of EpicSpawners are you using?

**Comment by cachondagames** [comment]
> What version of EpicSpawners are you using?
> Perhaps try downgrading to an earlier version, as the latest commit was 21st of July earlier versions probably work with it but newer versions don't

6.2 but I was able to downgrade to 3.1.6 R10 to get it to work
