### ISSUE TITLE
Not loading on start, Error 

### ISSUE THREAD

**Issue by storm0chaser** [novucs/factions-top#124]
[12:26:34 INFO]: [FactionsTop] Enabling FactionsTop v1.1.2
[12:26:34 INFO]: [FactionsTop] Configuration file has been successfully updated.
[12:26:34 ERROR]: Error occurred while enabling FactionsTop v1.1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/zcore/persist/MemoryBoard
        at net.novucs.ftop.hook.Factions16x.initialize(Factions16x.java:42) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_231]
        at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:340) ~[?:?]
        at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:132) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.zcore.persist.MemoryBoard
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        ... 15 more
[12:26:34 INFO]: [FactionsTop] Disabling FactionsTop v1.1.2
[12:26:34 INFO]: [FactionsTop] Preparing shutdown...
[12:26:34 INFO]: [FactionsTop] Shutting down chunk worth task...
[12:26:34 INFO]: [FactionsTop] Saving everything to database...
[12:26:34 INFO]: [FactionsTop] Terminating plugin services...
[12:26:34 ERROR]: Error occurred while disabling FactionsTop v1.1.2 (Is it up to date?)
java.lang.NullPointerException
        at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:171) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by Phoenix616** [comment]
Could you please provide some information about the Factions version that you are using?

**Comment by storm0chaser** [comment]
Do you have discord? It’s easier to provide information

**Comment by storm0chaser** [comment]
I’m using latest version of factionsuuid, does your plugin support that?

**Comment by Phoenix616** [comment]
The fix is included in the [latest dev build](https://ci.minebench.de/job/FactionsTop/).

**Comment by storm0chaser** [comment]
Hiya, 
Updated it to #14
Still having an issue with factionsuuid - Factions v1.6.9.5-U0.5.8-b218
[14:26:33 INFO]: [FactionsTop] Enabling FactionsTop v1.2.1-SNAPSHOT
[14:26:33 INFO]: [FactionsTop] Essentials found, using as economy backend.
[14:26:33 INFO]: [FactionsTop] Configuration file has been successfully updated.
[14:26:33 INFO]: [FactionsTop] H2 forcefully loaded, a reboot may be required.
[14:26:33 ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:h2:./plugins/FactionsTop/database
        at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:88) ~[?:?]
        at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:298) ~[?:?]
        at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:91) ~[?:?]
        at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:101) ~[?:?]
        at net.novucs.ftop.shade.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
        at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:24) ~[?:?]
        at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:19) ~[?:?]
        at net.novucs.ftop.FactionsTopPlugin.loadDatabase(FactionsTopPlugin.java:193) ~[?:?]
        at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(Unknown Source) ~[?:1.8.0_231]
        at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:81) ~[?:?]
        ... 19 more
[14:26:33 INFO]: [FactionsTop] Disabling FactionsTop v1.2.1-SNAPSHOT
[14:26:33 INFO]: [FactionsTop] Preparing shutdown...
[14:26:33 INFO]: [FactionsTop] Shutting down chunk worth task...
[14:26:33 INFO]: [FactionsTop] Saving everything to database...
[14:26:33 INFO]: [FactionsTop] Terminating plugin services...
[14:26:33 ERROR]: Error occurred while disabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
        at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:178) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594) [StellarSpigot.jar:git-TacoSpigot-04511af6]

**Comment by Phoenix616** [comment]
See #123
