### ISSUE TITLE
Still getting an error while using factionsuuid

### ISSUE THREAD

**Issue by storm0chaser** [novucs/factions-top#126]
[10:25:29 INFO]: [FactionsTop] Enabling FactionsTop v1.2.0
[10:25:29 INFO]: [FactionsTop] Essentials found, using as economy backend.
[10:25:29 ERROR]: Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/zcore/persist/MemoryBoard
        at net.novucs.ftop.hook.Factions0106.initialize(Factions0106.java:42) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_231]
        at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:371) ~[?:?]
        at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:138) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.zcore.persist.MemoryBoard
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        ... 15 more
[10:25:29 INFO]: [FactionsTop] Disabling FactionsTop v1.2.0
[10:25:29 INFO]: [FactionsTop] Preparing shutdown...
[10:25:29 INFO]: [FactionsTop] Shutting down chunk worth task...
[10:25:29 INFO]: [FactionsTop] Saving everything to database...
[10:25:29 INFO]: [FactionsTop] Terminating plugin services...
[10:25:29 ERROR]: Error occurred while disabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NullPointerException
        at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:177) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594) [StellarSpigot.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by Phoenix616** [comment]
You are using an outdated version of the plugin. Please update to the latest dev build as mentioned in #124

**Comment by storm0chaser** [comment]
I'm using the latest version from 
https://www.spigotmc.org/resources/f-top-factions-top-by-novucs.26905/

**Comment by storm0chaser** [comment]
#123 is h2-1.4.192? isn't my error different?

**Comment by Phoenix616** [comment]
Your error is the same as 124 and it's fixed in the code already. Use the latest development build, not the older release.

**Comment by storm0chaser** [comment]
Can you compile it for me please

**Comment by Phoenix616** [comment]
The build server linked in the repo mentioned has build jar files, just use these...
