### ISSUE TITLE
Error while enabling FactionsTop, but h2 file succesfully loaded?

### ISSUE THREAD

**Issue by DevelopmentHigh** [novucs/factions-top#129]
```
[11:18:09] [Server thread/INFO]: [FactionsTop] H2 successfully loaded via classpath.
[11:18:09] [Server thread/ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: General error: "java.lang.IllegalStateException: Unable to read the page at position 126718716129671 [1.4.200/6]" [50000-200]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
	at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:24) ~[?:?]
	at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:19) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.loadDatabase(FactionsTopPlugin.java:193) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:140) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Unable to read the page at position 126718716129671 [1.4.200/6]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505) ~[?:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:194) ~[?:?]
	at org.h2.message.DbException.convert(DbException.java:347) ~[?:?]
	at org.h2.engine.Database.openDatabase(Database.java:333) ~[?:?]
	at org.h2.engine.Database.<init>(Database.java:301) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:74) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:192) ~[?:?]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:166) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:29) ~[?:?]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152) ~[?:?]
	at org.h2.Driver.connect(Driver.java:69) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
	... 17 more
Caused by: java.lang.IllegalStateException: Unable to read the page at position 126718716129671 [1.4.200/6]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950) ~[?:?]
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2213) ~[?:?]
	at org.h2.mvstore.MVMap.readPage(MVMap.java:672) ~[?:?]
	at org.h2.mvstore.MVMap.readOrCreateRootPage(MVMap.java:688) ~[?:?]
	at org.h2.mvstore.MVMap.setRootPos(MVMap.java:682) ~[?:?]
	at org.h2.mvstore.MVStore.openMap(MVStore.java:576) ~[?:?]
	at org.h2.mvstore.MVStore.openMap(MVStore.java:535) ~[?:?]
	at org.h2.mvstore.MVStore.openMap(MVStore.java:516) ~[?:?]
	at org.h2.mvstore.MVStore.removeMap(MVStore.java:2742) ~[?:?]
	at org.h2.engine.Database.handleUpgradeIssues(Database.java:866) ~[?:?]
	at org.h2.engine.Database.open(Database.java:742) ~[?:?]
	at org.h2.engine.Database.openDatabase(Database.java:307) ~[?:?]
	at org.h2.engine.Database.<init>(Database.java:301) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:74) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:192) ~[?:?]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:166) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:29) ~[?:?]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152) ~[?:?]
	at org.h2.Driver.connect(Driver.java:69) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
	... 17 more
Caused by: java.lang.IllegalStateException: Unsupported type 17 [1.4.200/3]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950) ~[?:?]
	at org.h2.mvstore.type.ObjectDataType.newType(ObjectDataType.java:165) ~[?:?]
	at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:229) ~[?:?]
	at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:114) ~[?:?]
	at org.h2.mvstore.Page.read(Page.java:605) ~[?:?]
	at org.h2.mvstore.Page.read(Page.java:239) ~[?:?]
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2211) ~[?:?]
	at org.h2.mvstore.MVMap.readPage(MVMap.java:672) ~[?:?]
	at org.h2.mvstore.MVMap.readOrCreateRootPage(MVMap.java:688) ~[?:?]
	at org.h2.mvstore.MVMap.setRootPos(MVMap.java:682) ~[?:?]
	at org.h2.mvstore.MVStore.openMap(MVStore.java:576) ~[?:?]
	at org.h2.mvstore.MVStore.openMap(MVStore.java:535) ~[?:?]
	at org.h2.mvstore.MVStore.openMap(MVStore.java:516) ~[?:?]
	at org.h2.mvstore.MVStore.removeMap(MVStore.java:2742) ~[?:?]
	at org.h2.engine.Database.handleUpgradeIssues(Database.java:866) ~[?:?]
	at org.h2.engine.Database.open(Database.java:742) ~[?:?]
	at org.h2.engine.Database.openDatabase(Database.java:307) ~[?:?]
	at org.h2.engine.Database.<init>(Database.java:301) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:74) ~[?:?]
	at org.h2.engine.Engine.openSession(Engine.java:192) ~[?:?]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:166) ~[?:?]
	at org.h2.engine.Engine.createSession(Engine.java:29) ~[?:?]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173) ~[?:?]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152) ~[?:?]
	at org.h2.Driver.connect(Driver.java:69) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316) ~[?:?]
	at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
	... 17 more
```

**Comment by DevelopmentHigh** [comment]
I fix, sorry

**Comment by DevelopmentHigh** [comment]
Its broken config
