### ISSUE TITLE
TacoSpigot

### ISSUE THREAD

**Issue by Orgems** [novucs/factions-top#134]
Hello, plugin not working with taco spigot here is code

> [18:06:24 ERROR]: Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:h2:./plugins/FactionsTop/database
at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:88) ~[?:?]
at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:298) ~[?:?]
at net.novucs.ftop.shade.com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:91) ~[?:?]
at net.novucs.ftop.shade.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:101) ~[?:?]
at net.novucs.ftop.shade.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:24) ~[?:?]
at net.novucs.ftop.manager.DatabaseManager.create(DatabaseManager.java:19) ~[?:?]
at net.novucs.ftop.FactionsTopPlugin.loadDatabase(FactionsTopPlugin.java:192) ~[?:?]
at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:139) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-TacoSpigot-"95870a93"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.sql.SQLException: No suitable driver
at java.sql.DriverManager.getDriver(DriverManager.java:315) ~[?:1.8.0_242]
at net.novucs.ftop.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:81) ~[?:?]
... 19 more
> [18:06:24 INFO]: [FactionsTop] Disabling FactionsTop v1.2.0
> [18:06:24 INFO]: [FactionsTop] Preparing shutdown...
> [18:06:24 INFO]: [FactionsTop] Shutting down chunk worth task...
> [18:06:24 INFO]: [FactionsTop] Saving everything to database...
> [18:06:24 INFO]: [FactionsTop] Terminating plugin services...
> [18:06:24 ERROR]: Error occurred while disabling FactionsTop v1.2.0 (Is it up to date?)
java.lang.NullPointerException
at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:177) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-TacoSpigot-"95870a93"]

**Comment by Phoenix616** [comment]
You are not using the latest version, please update to the latest [build](https://ci.minebench.de/job/FactionsTop/) and see if the error persists.

**Comment by Orgems** [comment]
thanks

**Comment by Orgems** [comment]
Phoenix the error didnt get fixed

**Comment by Phoenix616** [comment]
Please provide the new error log.

**Comment by Orgems** [comment]
> [15:55:49 ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/data/MemoryBoard
at net.novucs.ftop.hook.Factions0106.initialize(Factions0106.java:41) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_242]
at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:389) ~[?:?]
at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:139) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-TacoSpigot-"95870a93"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.data.MemoryBoard
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-TacoSpigot-"95870a93"]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
... 15 more
> [15:55:49 INFO]: [FactionsTop] Disabling FactionsTop v1.2.1-SNAPSHOT
> [15:55:49 INFO]: [FactionsTop] Preparing shutdown...
> [15:55:49 INFO]: [FactionsTop] Shutting down chunk worth task...
> [15:55:49 INFO]: [FactionsTop] Saving everything to database...
> [15:55:49 INFO]: [FactionsTop] Terminating plugin services...
> [15:55:49 ERROR]: Error occurred while disabling FactionsTop v1.2.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:178) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [server.jar:git-TacoSpigot-"95870a93"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-TacoSpigot-"95870a93"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [server.jar:git-TacoSpigot-"95870a93"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Orgems** [comment]
new code
soorry for late reply

**Comment by Orgems** [comment]
phoenix are you there

**Comment by Phoenix616** [comment]
Please don't bump threads, that's just spam. Someone will get to your issue when they have the time to do so.
