### ISSUE TITLE
Faction Top Errors with EpicSpawners and Requested support already in Songoda Support

### ISSUE THREAD

**Issue by DJDanTheMan** [novucs/factions-top#143]
Hello, Here is the error log i have:
Error:
[15:47:11] [Server thread/ERROR]: Error occurred while enabling FactionsTop v1.2.1-SNAPSHOT (build 21) (Is it up to date?)
java.lang.NoSuchMethodError: com.songoda.epicspawners.EpicSpawners.getApi()Lcom/songoda/epicspawners/API/EpicSpawnersAPI;
	at net.novucs.ftop.hook.EpicSpawnersHook.initialize(EpicSpawnersHook.java:31) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.loadSpawnerStackerHook(FactionsTopPlugin.java:286) ~[?:?]
	at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:131) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:360) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:319) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[15:47:11] [Server thread/INFO]: [FactionsTop] Disabling FactionsTop v1.2.1-SNAPSHOT (build 2-1)
[15:47:11] [Server thread/INFO]: [FactionsTop] Preparing shutdown...
[15:47:11] [Server thread/INFO]: [FactionsTop] Shutting down chunk worth task...
[15:47:11] [Server thread/INFO]: [FactionsTop] Saving everything to database...
[15:47:11] [Server thread/INFO]: [FactionsTop] Terminating plugin services...
[15:47:11] [Server thread/ERROR]: Error occurred while disabling FactionsTop v1.2.1-SNAPSHOT (build 21) (Is it up to date?)
java.lang.NullPointerException
	at net.novucs.ftop.FactionsTopPlugin.onDisable(FactionsTopPlugin.java:178) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:360) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:319) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

I would like to request this to be updated, due to i have been using your plugin for a long period with no issues, for some unknown reason in epic spawners has made it impossible for me to reduce some lag issues that i've been having, I know if this had support added for the latest version of epic spawners it would assist me a lot more. Please consider my issue thanks for reading,

**Comment by Phoenix616** [comment]
Which version of EpicSpawners are you running?

**Comment by DJDanTheMan** [comment]
6.4.10 i was using when i got that error

**Comment by DJDanTheMan** [comment]
@Phoenix616 I have an update from the support ticket I made in songoda and got a response, from their lead developer sent me this:
![image](https://user-images.githubusercontent.com/74198936/98984661-6ba0a680-251a-11eb-99fd-51fd61f36718.png)

I hope you can update the plugin Api for epic spawners?

**Comment by Phoenix616** [comment]
Unfortunately they make it quite hard for anyone to support their plugin as they don't seem to release maven artifacts or provide any kind of development resources (as far as I can tell) so one has to somehow manually add some abstraction include it yourself.

**Comment by DJDanTheMan** [comment]
@Phoenix616 After speaking into songoda support discord, one of the admins sent me this that may help you fix the error https://github.com/songoda/EpicSpawners/tree/master/src/main/java/com/songoda/epicspawners/api/events.

**Comment by Phoenix616** [comment]
I know that that exists, but they don't provide a way to easily depend on their plugin with maven/gradle. Everyone trying to do that would have to setup something manually for that. If they want people to integrate with their plugin then they should offer easy ways to do that.

**Comment by DJDanTheMan** [comment]
@Phoenix616 After a second trip to the songoda support discord, you might be able to use this instead https://repo.songoda.com/repository/public/

**Comment by Phoenix616** [comment]
I took a look at their repo and apparently the don't include the latest version of the plugin? Not sure what is going on with their setup but this is kinda horrible lol

**Comment by DJDanTheMan** [comment]
@Phoenix616 After a second trip to the songoda support discord, here is what one of their admins said
![image](https://user-images.githubusercontent.com/74198936/99159079-40ac8300-26d1-11eb-9ff8-0776d574896f.png)

**Comment by Phoenix616** [comment]
Oof. Guess they don't want people to use and support their plugin... if anyone wants to PR a solution then feel free, I don't really feel like putting in unnecessary work for such a badly managed project.
