### ISSUE TITLE
/ftop doesn't work. 

### ISSUE THREAD

**Issue by ileftclick** [novucs/factions-top#146]
When I do /ftop, it just says /ftop [page]. I've tried to look for different f top plugins but I couldn't find any good ones. These are the errors in console.

[ERROR] Error occurred while enabling FactionsTop v1.2.0 (Is it up to date?)

java.lang.NoClassDefFoundError: org.slf4j.LoggerFactory

at net.novucs.ftop.shade.com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:50) ~[?:?]

at net.novucs.ftop.Settings.loadHikariConfig(Settings.java:442) ~[?:?]

at net.novucs.ftop.Settings.load(Settings.java:523) ~[?:?]

at net.novucs.ftop.FactionsTopPlugin.loadSettings(FactionsTopPlugin.java:367) ~[?:?]

at net.novucs.ftop.FactionsTopPlugin.onEnable(FactionsTopPlugin.java:138) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_272]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_272]

at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]

Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory

at java.net.URLClassLoader.findClass(URLClassLoader.java:591) ~[?:1.8.0_272]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953) ~[?:1.8.0_272]

at java.lang.ClassLoader.loadClass(ClassLoader.java:898) ~[?:1.8.0_272]

at java.lang.ClassLoader.loadClass(ClassLoader.java:881) ~[?:1.8.0_272]

... 28 more

**Comment by Phoenix616** [comment]
You are running an outdated build of the plugin (as well as an [extremely old](https://howoldisminecraft188.today/) server but I guess there is no way around that for you?), please test if the issue still occurs with the latest [dev build](https://ci.minebench.de/job/FactionsTop/).

**Comment by ileftclick** [comment]
it worked, thanks
