### ISSUE TITLE
When player does /ftop - error happens; when console does /ftop - works

### ISSUE THREAD

**Issue by TheJoshue** [novucs/factions-top#149]
Title says it all

Console /ftop
![image](https://user-images.githubusercontent.com/56804505/135712340-107f3184-428e-4940-b187-4072e32bf6ab.png)

Player ingame /ftop
![image](https://user-images.githubusercontent.com/56804505/135712354-74ec6d43-f71a-42e7-9969-cd8fe79dca0e.png)

Full error
```
[12:23:27 INFO]: TheJoshua issued server command: /ftop
[12:23:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ftop' in plugin FactionsTop v1.2.1-SNAPSHOT (build 22)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[flamepaper-1.8.8.jar:]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[flamepaper-1.8.8.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [flamepaper-1.8.8.jar:]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:762) [flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701) [flamepaper-1.8.8.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604) [flamepaper-1.8.8.jar:]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.Faction.getRelationTo(Lcom/massivecraft/factions/iface/RelationParticipator;)Lcom/massivecraft/factions/perms/Relation;
        at net.novucs.ftop.hook.Factions0106.getRelation(Factions0106.java:92) ~[?:?]
        at net.novucs.ftop.util.StringUtils.getRelationColor(StringUtils.java:37) ~[?:?]
        at net.novucs.ftop.command.TextCommand.sendTop(TextCommand.java:98) ~[?:?]
        at net.novucs.ftop.command.TextCommand.onCommand(TextCommand.java:47) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[flamepaper-1.8.8.jar:]
        ... 15 more
```

**Comment by Phoenix616** [comment]
They should really use a different plugin name if they don't care about staying compatible with the upstream's API, this is getting ridiculous. Unfortunately it's pretty much impossible to fix this besides writing a completely separate hook for this plugin as SaberFactions uses a different package for the returned Relation of the `getRelationTo` method.

I suggest using the old version that works for now.

**Comment by TheJoshue** [comment]
> They should really use a different plugin name if they don't care about staying compatible with the upstream's API, this is getting ridiculous. Unfortunately it's pretty much impossible to fix this besides writing a completely separate hook for this plugin as SaberFactions uses a different package for the returned Relation of the `getRelationTo` method.
> 
> I suggest using the old version that works for now.

build 13 from jenkins works with this
i wanted to ask will you ever update PAPI to 2.10.7+ hook because there are big difference?
and would you update the latest build 22 PAPi hook + build 13's PAPI hook and release it as "SaberFactions compatible" or at least send me in private (i can send you my discord)

I mean why i am asking for build#13, because it works with SaberFactions, and the PAPI hook that you'll update to bump to papi's 2.10.7+ version, you can literally copy-paste and implement to build13.

**Comment by TheJoshue** [comment]
I also wanted to ask will you compile this with java8 + java11 too (2 jars)

**Comment by Phoenix616** [comment]
> I also wanted to ask will you compile this with java8 + java11 too (2 jars)

This doesn't really have anything to do with this issue but the plugin is compiled for Java 8 which works on any version above it. (Realistically you should be running latest or at least latest LTS though (Java 17))

**Comment by 8bitheartbreak** [comment]
What factions plugin are you using? Looks like the factions hook is messing up either due to an outdated or unsupported factions plugin.
