### ISSUE TITLE
Server problem

### ISSUE THREAD

**Issue by NighteranceMC** [novucs/factions-top#41]
`[19:40:43] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to FactionsTop v5.9.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:369) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [minecraft_server.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: me/determined/ft/api/Factions
	at me.determined.factionstop.listeners.ChunkListener.checkChunk(ChunkListener.java:33) ~[?:?]
	at me.determined.factionstop.listeners.ChunkListener.onChunkUnload(ChunkListener.java:24) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[minecraft_server.jar:git-PaperSpigot-"8b18730"]
	... 11 more`

On my test server everything was working, when I uploaded to winscp files, was not working, weird, maybe easyer to look at code here : http://prntscr.com/fp98ry

**Comment by novucs** [comment]
That error is not from this plugin...
`me.determined.factionstop`
Also, next time you go to submit an error please put the stacktrace on https://gist.github.com/ so it is actually readable.
