### ISSUE TITLE
Flood error

### ISSUE THREAD

**Issue by SuperJogosDBZ** [novucs/factions-top#56]
On some occasions or console flood this error...

```
[Server thread/WARN]: [FactionsTop] Task #272 for FactionsTop v1.1.2 generated an exception
java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) ~[?:1.8.0_141]
	at java.util.LinkedList$ListItr.remove(LinkedList.java:921) ~[?:1.8.0_141]
	at net.novucs.ftop.manager.WorthManager.run(WorthManager.java:81) ~[?:?]
	at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:57) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

**Comment by novucs** [comment]
Thank you for bringing this to me. Please answer these questions as it'll allow me to debug:

Which version of factions are you using?
Are you running EpicSpawners? (if so, what version)

Someone is probably calling an event asynchronously and causing that CME. I've added a patch which should hopefully resolve that issue, please test and let me know how it goes. https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE

**Comment by SuperJogosDBZ** [comment]
Factions 2.10 and not using epicspawners.
I will test!
