### ISSUE TITLE
Error in console when executing any command

### ISSUE THREAD

**Issue by StalexB** [novucs/factions-top#67]
This error pops up in console everytime someone executes any command:

```
[18:15:11] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to FactionsTop v1.2.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1158) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [server.jar:git-PaperSpigot-fe4c7c8-d27e6d0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
```

**Comment by novucs** [comment]
The stack trace you have supplied is incomplete, I am unable to figure out what went wrong with this.

**Comment by darbyjack** [comment]
Novcus, this has happened on multiple servers I work on from time to time, it NEVER shows anything under the "caused by NPE", there has to be something on your end causing this. If there was more of a stacktrace I would've fixed this myself.

**Comment by novucs** [comment]
@darbyjack without the full stack trace, all I can tell is that the error is being caused by a call from Bukkit itself. Do you have a good method for reproducing this? If so, please do tell.

**Comment by darbyjack** [comment]
Hey there, I do not really have a definite way to reproduce this, I just know it's a common issue but it's just so weird that it doesn't show the full stacktrace. https://hastebin.com/cugepixawi.vbs here's one we got to produce a few hours ago. Although it looks somewhat the same as the original one.

**Comment by novucs** [comment]
@darbyjack sorry I'm on my phone right now, could you bring up that servers relevent source for `org.bukkit.command.PluginCommand`? It is possible that this is an issue with Bukkit itself, would be good to rule it out before hurting our heads.

**Comment by darbyjack** [comment]
How would I go about finding that? Usually when I look at my own stacktraces I see where in my plugin the issue is being called and not worrying about others.

**Comment by darbyjack** [comment]
Ya, I found it. How do I go about finding what I need? If Discord is easier, drop me a request (Glare
#8499)

**Comment by novucs** [comment]
@darbyjack I added you, though I suppose you've not got the notification. Either way, I figured the issue: https://github.com/novucs/factions-top/commit/61db0403b7e0caef679507a27825dcbe104eee25

Download here: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE

**Comment by darbyjack** [comment]
Alright, mind letting me know what your discord username is too? Sorry, I have about 80 request

**Comment by novucs** [comment]
@darbyjack billy#2404
