### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by NotAHackedCookie** [novucs/factions-top#71]
I use FactionsUUID and when I start the server after it loads everything it FactionsTop spams the console with this message: 

```
[15:44:27] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to FactionsTop v1.2.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:352) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
at net.novucs.ftop.hook.Factions0106.getFactionAt(Factions0106.java:36) ~[?:?]
at net.novucs.ftop.hook.FactionsHook.getFactionAt(FactionsHook.java:39) ~[?:?]
at net.novucs.ftop.manager.WorthManager.getFactionWorth(WorthManager.java:208) ~[?:?]
at net.novucs.ftop.manager.WorthManager.recalculate(WorthManager.java:357) ~[?:?]
at net.novucs.ftop.listener.WorthListener.recalculate(WorthListener.java:311) ~[?:?]
at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
... 10 more
```

**Comment by novucs** [comment]
The latest dev build has this resolved: https://drive.google.com/open?id=0B8XNBcgBSdHyWFRITE90QU9WZEE
