### ISSUE TITLE
Not compatible with ShopGuiPlus

### ISSUE THREAD

**Issue by ThelastFPS** [novucs/factions-top#85]
This plugin breaks Shopguiplus

**Comment by Phoenix616** [comment]
Please provide some more information how it breaks it. (What happens, are there any errors in the log, if so, which? Also what version are you using and please test if it happens with the [latest development build](https://ci.minebench.de/view/Various/job/FactionsTop/))

**Comment by xdMush** [comment]
Phoenix, It doesnt allow you to use /Shop, it says "Shop failed to load. Please check the server logs for errors" whenever the FactionsTop Plugin has been installed to you have a fix to this or no?

**Comment by Phoenix616** [comment]
Please provide the log in question. Without that there is no way to know what the issue is. (I'm also kinda surprised about it, this plugin doesn't do anything with shops? :thinking:)

**Comment by xdMush** [comment]
[19:04:39] [Server thread/WARN]: java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler
[19:04:39] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[19:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[19:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[19:04:39] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:04:39] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:04:39] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[19:04:39] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[19:04:39] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:150)
[19:04:39] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:122)
[19:04:39] [Server thread/WARN]: 	at net.brcdev.shopgui.provider.spawner.SpawnerSilkSpawnersProvider.hook(SpawnerSilkSpawnersProvider.java:16)
[19:04:39] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.setupSpawners(ShopGuiPlugin.java:325)
[19:04:39] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:143)
[19:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[19:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:04:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[19:04:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[19:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[19:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[19:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[19:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[19:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[19:04:39] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Phoenix616** [comment]
That is an error in ShopGuiPlus, not this plugin. I'm not sure why it would only occur when installing FactionsTop but I would guess it has something to do with the plugin load order. (FactionsTop soft-depends on SilkSpawners so it will load before) I suggest reporting that error to the author of that shop plugin.
